name:                angemalt
version:             0.1.0.0
github:              "dotKuro/angemalt"
license:             GPL-3.0-or-later
author:              "Alexander 'dotKuro' Kampf"
maintainer:          "mail@akampf.dev"
copyright:           "2020 Alexander Kampf"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/dotKuro/angemalt#readme>

dependencies:
- base >= 4.7 && < 5
- text 
- template
- split
- aeson
- bytestring
- containers
- optparse-applicative
- directory
- filepath


library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  angemalt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - angemalt

tests:
  angemalt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - angemalt
